### ISSUE TITLE
420R 1206 LED resistors difficult to source

### ISSUE THREAD

**Issue by pseudobacon** [Gondolindrim/Tsuki#3]
Hi the schematics call for 420 ohm 1206 sized resistors for the LEDs. This specific value and type is very hard to find may I suggest a more common value such as 330R or 470R?

**Comment by Gondolindrim** [comment]
Hey @pseudobacon !

Try using 390 ohms. Should be available in most component suppliers!

**Comment by pseudobacon** [comment]
Yep much easier to find. Just curious as to why 420 was chosen? It should just affect the brightness of the LED right?

**Comment by Gondolindrim** [comment]
The problem with LED resistors is that each LED color has a different forward voltage -- red has around 2.6V, green around 3 and blue around 3.4 . So the same value for these three will yield different current hence distinc lighting levels. If you make the math, 420 is the value that gives acceptable values for all three.
